### ISSUE TITLE
Add a Service registration SPI

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-stork#110]
Often, services that would use Service Discovery, would also like to register themselves to the Service Registry that is backing up the discovery.

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24759.

```yaml
organization: QuarkusIO
repository: quarkus
issue: 24759
url: https://github.com/quarkusio/quarkus/issues/24759
```
