### ISSUE TITLE
reconsider adding `type` to the load balancer and service discovery properties

### ISSUE THREAD

**Issue by michalszynkiewicz** [smallrye/smallrye-stork#22]
Right now the type of service discovery for a service is configured as follows:
```properties
dux.my-service.service-discovery=consul
dux.my-service.service-discovery.some-service-discovery-property=property-value
```

As @Ladicek pointed out, it is not good for YAML where users will end up with:
```yaml
dux:
  my-service:
    service-discovery:
      ~: consul
      some-service-discovery-property: property-value
```

I think we need to go back to:
```properties
dux.my-service.service-discovery.type=consul
dux.my-service.service-discovery.some-service-discovery-property=property-value
```
