### ISSUE TITLE
Provide an example of load balancer using "machine learning" to select the best service instance

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-stork#283]
This epic is about writing a how-to explaining how one can implement an advanced load balancer integrating machine learning to choose the best service instance.

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24761.

```yaml
organization: QuarkusIO
repository: quarkus
issue: 24761
url: https://github.com/quarkusio/quarkus/issues/24761
```
