### ISSUE TITLE
Improve service instance cache

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-stork#284]

**Comment by cescoffier** [comment]
@michalszynkiewicz @aureamunoz I've found a sticky note about that, but without much details. What do you have in mind?

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24757.

```yaml
organization: QuarkusIO
repository: quarkus
issue: 24757
url: https://github.com/quarkusio/quarkus/issues/24757
```
