### ISSUE TITLE
Improve release notes generation

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-stork#285]
Extend the release process to generate release notes:

- distinguish core/load-balancer/service-discovery (and maybe prefix with the type for SD and LB)
- list the breaking changes if any
- mention dependency update is a separated list

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24762.

```yaml
organization: QuarkusIO
repository: quarkus
issue: 24762
url: https://github.com/quarkusio/quarkus/issues/24762
```
