### ISSUE TITLE
New service discovery implementation based on Knative

### ISSUE THREAD

**Issue by aureamunoz** [smallrye/smallrye-stork#402]
We would need a new service discovery implementation in Stork for KNative. This SD locates the KNative service (and not the pods as we do for Kubernetes). It would not be possible to use load balancing. However, if you use KNative, load balancing can be handled there.

This SD would take a (Knative) service name as parameter and search for it in the current (or configured) namespace. It will not check if there are pods, just locate the service, resolve the name and return that name. It fails if no service can be found. You will never have more than one service (this needs to be verified when using revisions).

See [Quarkus #146](https://github.com/quarkusio/quarkus-super-heroes/issues/146)

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus-upstream-roadmap/issues/19.

```yaml
organization: QuarkusIO
repository: quarkus-upstream-roadmap
issue: 19
url: https://github.com/quarkusio/quarkus-upstream-roadmap/issues/19
```
